# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

from dataclasses import dataclass


@dataclass
class Response:
    """Response details from agent execution."""

    messages: list[str]
    """The list of response messages from the agent.

    Each message represents a text response generated by the agent during execution.
    Messages are serialized to JSON format for OpenTelemetry span attributes.
    An empty list is valid and represents no response messages.
    """
